services:
  opensearch:
    image: opensearchproject/opensearch:2.19.0
    labels:
      kompose.service.type: ClusterIP
      kompose.volume.size: 1Gi
    ports:
      - 9200
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=${OPENSEARCH_JAVA_OPTS:-{{ .Values.opensearchJavaOpts }}}"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    restart: "always"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  ollama:
    image: ollama/ollama:0.5.11
    labels:
      kompose.service.type: ClusterIP
      kompose.volume.size: 5Gi
    ports:
      - 11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    volumes:
      - ollama_data:/root/.ollama
    restart: "always"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  ouragboros:
    build: .
    image: schrodingersket/ouragboros:0.0.1
    labels:
      kompose.service.type: LoadBalancer
      kompose.service.expose: "true"
      kompose.volume.size: 3Gi
    ports:
      - 8501:8501
    environment:
      # Loaded from .env
      #
      - "OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-{{ .Values.ollamaBaseUrl }}}"
      - "OLLAMA_MODEL_DEFAULT=${OLLAMA_MODEL_DEFAULT:-{{ .Values.ollamaModelDefault }}}"
      - "SENTENCE_TRANSFORMERS_HOME=${SENTENCE_TRANSFORMERS_HOME:-{{ .Values.sentenceTransformersHome }}}"
      - "PDF_PARSER_MODEL=${PDF_PARSER_MODEL:-{{ .Values.pdfParserModel }}}"
      - "OPENSEARCH_BASE_URL=${OPENSEARCH_BASE_URL:-{{ .Values.opensearchBaseUrl }}}"
      - "OPENSEARCH_INDEX_PREFIX=${OPENSEARCH_INDEX_PREFIX:-{{ .Values.opensearchIndexPrefix }}}"
      - "PREFER_OPENSEARCH=${PREFER_OPENSEARCH:-{{ .Values.preferOpensearch }}}"
      - "HUGGINGFACE_EMBEDDING_MODEL_DEFAULT=${HUGGINGFACE_EMBEDDING_MODEL_DEFAULT:-{{ .Values.huggingfaceEmbeddingModelDefault }}}"
      - "HUGGINGFACE_FINETUNED_EMBEDDING_MODEL=${HUGGINGFACE_FINETUNED_EMBEDDING_MODEL:-{{ .Values.huggingfaceFinetunedEmbeddingModel }}}"
    volumes:
      - ouragboros_models:/app/models
    restart: "always"
    depends_on:
      - ollama
      - opensearch
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
            - data/
            - models/
        - action: rebuild
          path: ./uv.lock

volumes:
  opensearch_data:
  ollama_data:
  ouragboros_models:
