apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s.yaml

patches:
  - target:
      kind: Deployment
      name: ollama
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1
  - target:
      kind: Deployment
      name: ouragboros
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            nvidia.com/gpu: 1
          limits:
            nvidia.com/gpu: 1
