apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: opensearch-data
  name: opensearch-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
