apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: ouragboros-models
  name: ouragboros-models
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
