#!/bin/bash

# Test script for OuRAGboros API service
echo "🧪 TESTING OURAGBOROS API SERVICE"
echo "=================================="
echo ""

echo "📊 Service Configuration:"
kubectl get svc ouragboros -n ouragboros

echo ""
echo "🎯 Service Endpoints:"
kubectl get endpoints ouragboros -n ouragboros

echo ""
echo "🔗 Setting up port forwarding for both services..."
echo "(You'll need to run these commands in separate terminals)"
echo ""

echo "📋 TESTING INSTRUCTIONS:"
echo "========================"
echo ""
echo "1. 🌐 START PORT FORWARDING (run in separate terminals):"
echo "   Terminal 1 (Streamlit UI):"
echo "   kubectl port-forward -n ouragboros svc/ouragboros 8501:8501"
echo ""
echo "   Terminal 2 (FastAPI REST):"
echo "   kubectl port-forward -n ouragboros svc/ouragboros 8001:8001"
echo ""

echo "2. 🧪 TEST STREAMLIT UI:"
echo "   Open: http://localhost:8501"
echo "   Should show: OuRAGboros Streamlit interface"
echo ""

echo "3. 🧪 TEST FASTAPI REST API:"
echo "   Test basic endpoint:"
echo "   curl http://localhost:8001"
echo ""
echo "   Test API documentation:"
echo "   curl http://localhost:8001/docs"
echo ""
echo "   Test chat endpoint:"
echo "   curl -X POST http://localhost:8001/ask \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{"
echo "       \"query\": \"What is machine learning?\","
echo "       \"embedding_model\": \"thellert/physbert_cased\","
echo "       \"llm_model\": \"llama3.1\","
echo "       \"prompt\": \"Answer briefly and clearly.\","
echo "       \"use_rag\": false"
echo "     }'"
echo ""

echo "4. 🔍 CHECK BOTH SERVICES ARE RUNNING:"
echo "   Check container logs:"
echo "   kubectl logs -n ouragboros -f deployment/ouragboros"
echo ""

echo "📋 EXPECTED RESULTS:"
echo "====================" 
echo "✅ Streamlit UI: Interactive web interface at port 8501"
echo "✅ FastAPI REST: JSON API responses at port 8001"
echo "✅ /docs endpoint: FastAPI auto-generated API documentation"
echo "✅ /ask endpoint: Chat/Q&A functionality via REST API"
echo ""

echo "🚀 CHATBOT FRONTEND INTEGRATION:"
echo "================================"
echo "Your chatbot frontend can now use the REST API at:"
echo "  • Endpoint: http://localhost:8001/ask (when port-forwarded)"
echo "  • Method: POST"
echo "  • Content-Type: application/json"
echo ""
echo "Required parameters:"
echo "  • query: User's question"
echo "  • embedding_model: thellert/physbert_cased"  
echo "  • llm_model: llama3.1"
echo "  • prompt: System prompt for the LLM"
echo ""
echo "Optional parameters:"
echo "  • use_rag: true/false (enable document retrieval)"
echo "  • files: Array of uploaded documents"
echo "  • history: Previous conversation context"
echo ""

echo "💡 FOR PRODUCTION:"
echo "=================="
echo "Replace localhost:8001 with your cluster's service URL or ingress"
echo "Configure proper authentication and rate limiting as needed"