# Optimized configuration for S3DF with volume constraints
# Single replicas with massive resources - better than multiple replicas with shared volume conflicts
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s.yaml

patches:
  - target:
      kind: Deployment
      name: ollama
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 16000m
            memory: 64Gi
          limits:
            cpu: 32000m
            memory: 128Gi
  - target:
      kind: Deployment
      name: ouragboros
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 8000m
            memory: 32Gi
          limits:
            cpu: 16000m
            memory: 64Gi
  - target:
      kind: Deployment
      name: opensearch
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 4000m
            memory: 16Gi
          limits:
            cpu: 8000m
            memory: 32Gi